version: "3.8"

networks:
  backend:
    driver: bridge

services:
  db:
    build:
      context: ./docker/mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
  redis:
    image: redis:4.0
    container_name: redis
    ports:
      - "6382:6379"
    networks:
      - backend
  app-id:
    build:
      context: ./fiap-postech-hackathon-app
    volumes:
      - ./fiap-postech-hackathon-app:/var/www/html
      - ./fiap-postech-hackathon-app/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./fiap-postech-hackathon-app/docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - 8080:80
    networks:
      - backend
    environment:
      - "DB_HOST=db"
    depends_on:
      - db
      - redis